package keygen

import (
	"bytes"
	"fmt"

	"github.com/fil-forge/ucantool/pkg/ucandelegate"
)

// Proof is a UCAN delegation a service needs at startup.
//
// Proofs are not secrets. A delegation is a signed statement that one DID may
// invoke a command on another, and it is useless without the audience's own
// key, which is why smelt commits these to git and this project stores them as
// plaintext SSM parameters.
//
// They are filed under the service that *reads* them rather than the one that
// signs them, so each task's execution role still needs only its own prefix.
type Proof struct {
	// Consumer is the SSM service prefix the proof is stored under.
	Consumer string
	// Name is the parameter name under that prefix.
	Name string
	// Issuer is the service whose identity key signs the delegation.
	Issuer string

	issuerDID string
	audience  string
	subject   string
	commands  []string
	codec     string // "" is a bare DAG-CBOR delegation; otherwise a container
}

// Proofs returns the delegations this deployment needs, given the did:web of
// each service.
//
// Three of smelt's five apply here. The piri-0 and hilt-ingot proofs belong to
// the storage-node side of the stack, which this project does not deploy.
//
// The first two exist only to satisfy the delegator's startup validation: it
// requires an indexing-service and an egress-tracking delegation even though
// neither service runs yet. That is why their identity keys are minted at all.
func Proofs(did map[string]string) []Proof {
	return []Proof{
		{
			Consumer:  "delegator",
			Name:      "indexing-service-proof",
			Issuer:    "indexer",
			issuerDID: did["indexer"],
			audience:  did["delegator"],
			subject:   did["indexer"],
			commands:  []string{"/claim/cache"},
		},
		{
			Consumer:  "delegator",
			Name:      "egress-tracking-proof",
			Issuer:    "etracker",
			issuerDID: did["etracker"],
			audience:  did["delegator"],
			subject:   did["etracker"],
			commands:  []string{"/egress/track"},
		},
		// hilt presents this to sprue when registering tenants as customers.
		// hilt's loader parses a UCAN *container*, not a bare delegation, hence
		// the codec.
		{
			Consumer:  "hilt",
			Name:      "upload-proof",
			Issuer:    "sprue",
			issuerDID: did["sprue"],
			audience:  did["hilt"],
			subject:   did["sprue"],
			commands:  []string{"/customer/add"},
			codec:     "base64+gzip",
		},
	}
}

// IssueProof signs a delegation with the issuer's private key.
//
// The bytes match what `ucantool delegate` writes, including its rule that
// textual container codecs end with a newline while raw ones do not. That is
// carried by ucandelegate.Result rather than reimplemented here, so a proof
// regenerated by this Lambda is byte-identical to one smelt committed.
//
// The key is passed as PEM bytes rather than a path on purpose: the file-based
// API would mean writing a private key to the Lambda's /tmp to satisfy a
// signature.
func IssueProof(issuerPEM []byte, proof Proof) (string, error) {
	result, err := ucandelegate.IssueFromPEM(issuerPEM, ucandelegate.Request{
		IssuerDIDWeb:   proof.issuerDID,
		Audience:       proof.audience,
		Subject:        proof.subject,
		Commands:       proof.commands,
		ContainerCodec: proof.codec,
		// No expiration: these authorise startup-time capabilities between
		// services we operate, and an expiry would take a service down at a
		// time nobody chose. smelt makes the same call.
	})
	if err != nil {
		return "", fmt.Errorf("issue %s proof for %s: %w", proof.Name, proof.Consumer, err)
	}

	var out bytes.Buffer
	if _, err := result.WriteTo(&out); err != nil {
		return "", fmt.Errorf("encode %s proof: %w", proof.Name, err)
	}
	return out.String(), nil
}
